# It directly uses autowarefoundation/autoware-github-actions for now
# but may change using Futu-reADS/autoware-github-actions
# that will be forked or mirrored from the original

name: build-and-test

on:
  push:
  ### schedule:
  ###   - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build-and-test:
    ### if: ${{ github.event_name != 'push' || github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: ros:humble
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      - name: Install dependencies
        run: |
          apt-get update

      - name: Debug
        run: |
          ls -l /etc/resolv.conf && nl -ba /etc/resolv.conf || true
          type dig || sudo apt-get install -y bind9-dnsutils
          dig github.com || true
          type ip || sudo apt-get install -y iproute2
          ip addr || ifconfig || true
          type systemctl || sudo apt-get install -y systemctl
          systemctl status 'network*' || true

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Configure SSH key pair
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          nl -ba ~/.ssh/known_hosts || true
          type ssh-keyscan || sudo apt-get install -y openssh-client
          nl -ba ~/.ssh/known_hosts || true
          ssh-keyscan github.com > ~/.ssh/known_hosts
          nl -ba ~/.ssh/known_hosts || true
          ssh -T github.com || true
          echo "Host github.com" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          ssh -T github.com || true
          nl -ba ~/.ssh/config
          ls -lR ~/.ssh

      - name: Check build_depends.repos
        id: check-file
        run: |
          if [ -f build_depends.repos ]; then
            echo "build_depends_repos=true" >> $GITHUB_OUTPUT
          else
            echo "build_depends_repos=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy our latest autoware.repos
        if: ${{ steps.check-file.outputs.build_depends_repos != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: Futu-reADS/autoware.FTD
          sparse-checkout: |
            autoware.repos
          sparse-checkout-cone-mode: false
          path: autoware.FTD
      - run: |
          cd autoware.FTD
          cp autoware.repos ../build_depends.repos
          touch AMENT_IGNORE COLCON_IGNORE

      - name: Debug vcs
        run: |
          mkdir -p dependency_ws
          vcs import --debug dependency_ws < build_depends.repos || true

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      ### - name: Upload coverage to CodeCov
      ###   if: ${{ steps.test.outputs.coverage-report-files != '' }}
      ###   uses: codecov/codecov-action@v5
      ###   with:
      ###     files: ${{ steps.test.outputs.coverage-report-files }}
      ###     token: ${{ secrets.CODECOV_TOKEN }}
      ###     fail_ci_if_error: false
      ###     verbose: true
      ###     flags: total

      - name: Show disk space after the tasks
        run: df -h
