# It directly uses autowarefoundation/autoware-github-actions for now
# but may change using Futu-reADS/autoware-github-actions
# that will be forked or mirrored from the original

name: build-and-test

on:
  push:
  ### schedule:
  ###   - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build-and-test:
    ### if: ${{ github.event_name != 'push' || github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: ros:humble
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      - name: Install dependencies
        run: |
          apt-get update

      - name: Debug ssh-keyscan
        run: |
          apt-add-repository -L || true
          apt-cache pkgnames
          apt-cache search '.*ssh-keyscan.*' || true
          dpkg -L openssh-client || true
          apt list --installed || true
          sudo apt-get install -y openssh-client || true

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Configure SSH key pair
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          type ssh-keyscan || {
            apt-cache pkgnames
            apt-cache search '.*ssh-keyscan.*'
            dpkg -L openssh-client
            sudo apt-get install openssh-client
          }
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Check build_depends.repos
        id: check-file
        run: |
          if [ -f build_depends.repos ]; then
            echo "::set-output name=build_depends_repos::true"
          else
            echo "::set-output name=build_depends_repos::false"
          fi
          ls -lR

      - name: Copy our latest autoware.repos
        if: ${{ steps.check-file.outputs.build_depends_repos != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: Futu-reADS/autoware.FTD
          fetch-depth: 2
          sparse-checkout: |
            autoware.repos
          sparse-checkout-cone-mode: false
          path: autoware.FTD
      - run: |
          cd autoware.FTD
          git checkout HEAD^
          cp autoware.repos ../build_depends.repos
          touch AMENT_IGNORE COLCON_IGNORE
          ls -lR

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      ### - name: Upload coverage to CodeCov
      ###   if: ${{ steps.test.outputs.coverage-report-files != '' }}
      ###   uses: codecov/codecov-action@v5
      ###   with:
      ###     files: ${{ steps.test.outputs.coverage-report-files }}
      ###     token: ${{ secrets.CODECOV_TOKEN }}
      ###     fail_ci_if_error: false
      ###     verbose: true
      ###     flags: total

      - name: Show disk space after the tasks
        run: df -h
