# It directly uses autowarefoundation/autoware-github-actions for now
# but may change using Futu-reADS/autoware-github-actions
# that will be forked or mirrored from the original

name: build-and-test

on:
  push:
  ### schedule:
  ###   - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build-and-test:
    ### if: ${{ github.event_name != 'push' || github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: ros:humble
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      ### - name: Install dependencies
      ###   run: |
      ###     apt-get update

      ### - name: Debug
      ###   run: |
      ###     ls -l /etc/resolv.conf && nl -ba /etc/resolv.conf || true
      ###     type dig || sudo apt-get install -y bind9-dnsutils
      ###     dig github.com || true
      ###     type ip || sudo apt-get install -y iproute2
      ###     ip addr || ifconfig || true
      ###     type systemctl || sudo apt-get install -y systemctl
      ###     systemctl status 'network*' || true

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      ### - name: Configure SSH key pair
      ###   run: |
      ###     sudo mkdir -p ~root/.ssh
      ###     sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~root/.ssh/id_rsa
      ###     sudo chmod 600 ~root/.ssh/id_rsa
      ###     sudo nl -ba ~root/.ssh/known_hosts || true
      ###     type ssh-keyscan || sudo apt-get install -y openssh-client
      ###     sudo nl -ba ~root/.ssh/known_hosts || true
      ###     sudo ssh-keyscan github.com > ~root/.ssh/known_hosts
      ###     sudo nl -ba ~root/.ssh/known_hosts || true
      ###     ssh -vT git@github.com || true
      ###     sudo ssh -i ~root/.ssh/id_rsa -vT git@github.com || true
      ###     sudo ls -lR ~root/.ssh

      - name: Check build_depends.repos
        id: check-file
        run: |
          if [ -f build_depends.repos ]; then
            echo "build_depends_repos=true" >> $GITHUB_OUTPUT
          else
            echo "build_depends_repos=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy our latest autoware.repos
        if: ${{ steps.check-file.outputs.build_depends_repos != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: Futu-reADS/autoware.FTD
          ### sparse-checkout: |
          ###   autoware.repos
          ### sparse-checkout-cone-mode: false
          path: autoware.FTD
      - run: |
          cd autoware.FTD
          cp autoware.repos ../build_depends.repos
          ### Do not watch here
          touch AMENT_IGNORE COLCON_IGNORE

      - name: Debug colcon build
        run: |
          ### Set git credential
          git config --global credential.helper store
          echo "url=${{ github.server_url }}" > ~/url-username-password.txt
          echo "username=${{ github.actor }}" >> ~/url-username-password.txt
          echo "password=${{ secrets.UNITTEST_WORKFLOW_TOKEN }}" >> ~/url-username-password.txt
          git credential approve < ~/url-username-password.txt
          ### Here retrieve dependent packages
          mkdir -p dependency_ws
          cat build_depends.repos \
          | sed 's/git@github.com:/https:\/\/github.com\//' \
          | vcs import dependency_ws || true
          ### Install dependent packages
          sudo apt-get update
          sudo apt-get install -y ros-humble-autoware-common-msgs
          sudo apt-get install -y libunwind-dev
          ### Maybe rosdep needed
          rosdep init || true
          rosdep update
          rosdep install --verbose --from-paths dependency_ws --ignore-src -r -y
          ### Here manually colcon build
          export MAKEFLAGS="-j 4"
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 4
          ### # In advance, create *Config.cmake
          ### for PKG in \
          ###     autoware_auto_msgs \
          ###     autoware_auto_system_msgs \
          ###     autoware_adapi_v1_msgs \
          ###     tier4_control_msgs \
          ###     tier4_system_msgs \
          ###     autoware_bridge_msgs \
          ###     ftd_master_msgs \
          ###     ; do
          ###   find dependency_ws \
          ###     -type f \
          ###     -path "*/$PKG/CMakeLists.txt" \
          ###     -execdir pwd \; \
          ###   | {
          ###     read -r WORKDIR &&
          ###     cd "$WORKDIR" &&
          ###     cmake .
          ###   } || exit 1
          ### done

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}
          token: ${{ secrets.UNITTEST_WORKFLOW_TOKEN }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}
          token: ${{ secrets.UNITTEST_WORKFLOW_TOKEN }}

      ### - name: Upload coverage to CodeCov
      ###   if: ${{ steps.test.outputs.coverage-report-files != '' }}
      ###   uses: codecov/codecov-action@v5
      ###   with:
      ###     files: ${{ steps.test.outputs.coverage-report-files }}
      ###     token: ${{ secrets.CODECOV_TOKEN }}
      ###     fail_ci_if_error: false
      ###     verbose: true
      ###     flags: total

      - name: Show disk space after the tasks
        run: df -h
